stages:
  - Test

test:
  image: node:latest
  stage: Test
  script:
    - npm ci
    - npm run start:ci &
    - npm install
    - npm install mochawesome-merge
    - npm install del-cli
    - npm run Cypress:tests
