stages:
  - Test

test:
  image: node:latest
  stage: Test
  script:
    - npm ci
    - Xvfb :99 &
    - export DISPLAY=:99
    - npm install
    - npm install mochawesome-merge
    - npm install del-cli
    - npm run Cypress:tests
